#  ┳┳┓┏┓┏┳┓┳┳┏┓┏┓┳┓  ┓┏┓┳┏┳┓┏┳┓┓┏
#  ┃┃┃┣┫ ┃ ┃┃┃┓┣ ┃┃━━┃┫ ┃ ┃  ┃ ┗┫
#  ┛ ┗┛┗ ┻ ┗┛┗┛┗┛┛┗  ┛┗┛┻ ┻  ┻ ┗┛
#                                


# Core Colors
background            #171216
foreground            #ebdfe6
selection_foreground  #eeb4ea
selection_background  #4a204b
cursor                #eeb4ea
cursor_text_color     #171216

# Regular Colors
color0  #171216               
color1  #ffb4ab                 
color2  #eeb4ea               
color3  #f6b8aa              
color4  #ffd6f9  
color5  #f6dbf0
color6  #d9bfd4             
color7  #ebdfe6            

# Bright Colors
color8  #3e373c         
color9  #ffb4ab                  
color10 #eeb4ea                
color11 #f6b8aa               
color12 #ffd6f9   
color13 #f6dbf0 
color14 #d9bfd4              
color15 #ebdfe6             
