#  ┳┳┓┏┓┏┳┓┳┳┏┓┏┓┳┓  ┓┏┓┳┏┳┓┏┳┓┓┏
#  ┃┃┃┣┫ ┃ ┃┃┃┓┣ ┃┃━━┃┫ ┃ ┃  ┃ ┗┫
#  ┛ ┗┛┗ ┻ ┗┛┗┛┗┛┛┗  ┛┗┛┻ ┻  ┻ ┗┛
#                                


# Core Colors
background            #0f1512
foreground            #dee4e0
selection_foreground  #87d6bc
selection_background  #00382b
cursor                #87d6bc
cursor_text_color     #0f1512

# Regular Colors
color0  #0f1512               
color1  #ffb4ab                 
color2  #87d6bc               
color3  #a8cbe2              
color4  #a3f2d7  
color5  #cee9dd
color6  #b2ccc1             
color7  #dee4e0            

# Bright Colors
color8  #343b38         
color9  #ffb4ab                  
color10 #87d6bc                
color11 #a8cbe2               
color12 #a3f2d7   
color13 #cee9dd 
color14 #b2ccc1              
color15 #dee4e0             
