#  ┳┳┓┏┓┏┳┓┳┳┏┓┏┓┳┓  ┓┏┓┳┏┳┓┏┳┓┓┏
#  ┃┃┃┣┫ ┃ ┃┃┃┓┣ ┃┃━━┃┫ ┃ ┃  ┃ ┗┫
#  ┛ ┗┛┗ ┻ ┗┛┗┛┗┛┛┗  ┛┗┛┻ ┻  ┻ ┗┛
#                                


# Core Colors
background            #0f1417
foreground            #dee3e6
selection_foreground  #8ad0ee
selection_background  #003545
cursor                #8ad0ee
cursor_text_color     #0f1417

# Regular Colors
color0  #0f1417               
color1  #ffb4ab                 
color2  #8ad0ee               
color3  #c5c3ea              
color4  #bce9ff  
color5  #cfe6f2
color6  #b4cad5             
color7  #dee3e6            

# Bright Colors
color8  #353a3d         
color9  #ffb4ab                  
color10 #8ad0ee                
color11 #c5c3ea               
color12 #bce9ff   
color13 #cfe6f2 
color14 #b4cad5              
color15 #dee3e6             
