include colors.conf


font_family  Nerd Font Mono Bold FantasqueSansM
font_size 16.0
bold_font auto
italic_font auto
bold_italic_font auto

background_opacity .7
dynamic_background_opacity 1
confirm_os_window_close 0

linux_display_server auto

scrollback_lines 2000
wheel_scroll_min_lines 1

enable_audio_bell no

window_padding_width 4

selection_foreground none
selection_background none

map ctrl+c copy_to_clipboard
map ctrl+v paste_from_clipboard

map ctrl+equal  change_font_size all +0.5
map ctrl+plus   change_font_size all +0.5
map ctrl+minus  change_font_size all -0.5
map ctrl+0      change_font_size all 0
