exec-once = qs 
# exec-once = echo $(jq .hyprland.batteryMax ~/.config/quickshell/vars/settings.json) > /sys/class/power_supply/BAT1/charge_control_end_threshold
exec-once = hypridle
exec-once = swww-daemon
exec-once = hyprctl setcursor Bibata-Modern-Classic 24

