$mainMod = SUPER
$call = qs ipc call
$wallpapersPath = ~/.config/walls/Wallpapers/

# a submap to opem apps
bind = $mainMod, F, submap, apps

submap = apps , reset

binde = , G, exec, firefox
binde = , H, exec, kitty nvim ~/.config/hypr/
binde = , Q, exec, kitty nvim ~/.config/quickshell/
binde = , K, exec, kitty nvim ~/.config/kitty/
binde = , D, exec, kitty nvim ~/dotfiles/

bind = $mainMod, F, submap, reset
submap = reset

bind = $mainMod, tab, submap, quickshell
submap = quickshell , reset

bind = , tab, exec, $call ui toggleSettings
bind = , Q, exec, qs kill -p ~/.config/quickshell/services/WallpaperPicker.qml|| qs -p ~/.config/quickshell/services/WallpaperPicker.qml
bind = , W, exec, $call wallpaper wallpaper $(find $wallpapersPath -type f | shuf -n 1)

bind = $mainMod, R, submap, reset
submap = reset


bind = $mainMod, E, exec, kitty yazi
bind = $mainMod, T, exec, kitty
bind = $mainMod, W, exec, firefox
bind = $mainMod, R, exec, $call ui launchLauncher
bind = $mainMod SHIFT, M, exit
bind = $mainMod, C, killactive,
bind = $mainMod, SPACE, togglefloating,
bind = $mainMod, B, pin
bind = $mainMod, D, fullscreen, 1
bind = $mainMod SHIFT, D, fullscreen

bind = $mainMod , F3, exec, hyprshade toggle reading
bind = $mainMod , F2, exec, hyprshade toggle step
bind = $mainMod , F1, exec, hyprshade toggle amoled
bind = $mainMod SHIFT, S, exec, hyprshot -m region -z -o ~/Pictures/Screenshots/
bind = $mainMod SHIFT, C, exec, hyprpicker -a
bind = $mainMod SHIFT, B, exec, qs kill -p ~/.config/quickshell/ || qs -p ~/.config/quickshell/ 

# Example special workspace (scratchpad)
bind = $mainMod, S, togglespecialworkspace, magic
bind = $mainMod CTRL, S, movetoworkspace, special:magic
bind = $mainMod, G, togglespecialworkspace, utils
bind = $mainMod CTRL, G, movetoworkspace, special:utils

bind = $mainMod CTRL, W, movetoworkspace, e+0

# Scroll through existing workspaces with mainMod + scroll
bindm = $mainMod, mouse:272, movewindow      # ALT + LMB: Move a window by dragging more than 10px.
bindc = $mainMod, mouse:272, togglefloating  # ALT + LMB: Floats a window by clicking
bind = $mainMod, mouse_down, workspace, +1
bind = $mainMod, mouse_up, workspace, -1
bind = $mainMod, k, workspace, +1
bind = $mainMod, j, workspace, -1
bind = $mainMod SHIFT, j, movetoworkspace, -1
bind = $mainMod SHIFT, k, movetoworkspace, +1
bind = $mainMod , h,cyclenext

# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = $mainMod, A, movewindow
bindm = $mainMod + SHIFT, A, resizewindow

$musicOsdCmd = $call ui toggleMusicOsd $(playerctl -p spotify volume) 
bind = ,XF86Next_VMode, exec, playerctl --player=spotify next && $musicOsdCmd
bind = ,XF86Prev_VMode, exec, playerctl --player=spotify previous && $musicOsdCmd
bind = ,XF86AudioRaiseVolume,exec, playerctl --player=spotify volume 0.05+ && $musicOsdCmd
bind = ,XF86AudioLowerVolume,exec, playerctl --player=spotify volume 0.05- && $musicOsdCmd
bind = ,XF86AudioPlay, exec, playerctl --player=spotify play-pause || playerctl  play-pause && mpc toggle
bind = ,XF86AudioPlay, exec, $musicOsdCmd
bind = $mainMod,XF86AudioPlay, exec, playerctl  play-pause && mpc toggle
bindel = ,XF86MonBrightnessUp, exec, brightnessctl -e4 -n2 set 5%+
bindel = ,XF86MonBrightnessDown, exec, brightnessctl -e4 -n2 set 5%-
