# Ignore maximize requests from apps. You'll probably like this.
layerrule = animation slide left, match:namespace qs-music-osd
layerrule = animation slide bottom, match:namespace qs-launcher

windowrule {
  name = windowrule-1
  suppress_event = maximize
  match:class = .*
}

# Fix some dragging issues with XWayland
windowrule {
  name = windowrule-2
  no_focus = on
  match:class = ^$
  match:title = ^$
  match:xwayland = 1
  match:float = 1
  match:fullscreen = 0
  match:pin = 0
}


windowrule {
  name = waypaper-float
  float = on
  match:class = waypaper
}


windowrule {
  name = spotify-rule
  workspace = special:utils silent
  rounding = 0
  opacity = 0.7
  match:class = ^(spotify)$
}
windowrule {
  name = quickshell-setting
  float = yes
  opacity = 0.9
  rounding = 16
  match:title = Settings
}




workspace = special:utils, gapsin:0, gapsout:90
workspace = special:magic, gapsin:0, gapsout:30
