$background = rgb(1E1E1B)
$foreground = rgb(F7F1D9)

$color0  = rgb(454441)
$color1  = rgb(8C5426)
$color2  = rgb(795E40)
$color3  = rgb(8D6B49)
$color4  = rgb(6D7886)
$color5  = rgb(BC8C5E)
$color6  = rgb(AEA16E)
$color7  = rgb(EBE2C1)

$color8  = rgb(A49E87)
$color9  = rgb(BB7033)
$color10 = rgb(A17D56)
$color11 = rgb(BC8F62)
$color12 = rgb(91A0B2)
$color13 = rgb(FABA7E)
$color14 = rgb(E8D693)
$color15 = rgb(EBE2C1)
